[package]
name = "miniaturo"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
description = "A RAW image thumbnailer."
edition = "2018"
license = "GPL-3.0+"

[dependencies]
anyhow = "1"
clap = { version = "3.0.0-beta.2", features = ["std", "derive", "cargo"], default-features = false }
image = { version = "0.23", features = ["png", "jpeg", "tiff"], default-features = false }
libopenraw-rs = { git = "https://gitlab.freedesktop.org/libopenraw/libopenraw-rs.git", rev = "f992e4ffd132dde852226bd13af1ea6d0a15e42e" }

[build-dependencies]

[profile.release]
lto = true
