//! Safe wrapper around the libopenraw FFI.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]

/// Raw FFI bindings generated by bindgen.
#[allow(dead_code)]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
