on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  test:
    name: run tests
    strategy:
      matrix:
        rust: [1.74.1, stable]
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Install Rust
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      # Build
      - name: Build
        run: cargo build --all-features

      # Run tests
      - name: Download test images
        run: python3 tests/download-test-images.py
      - name: Run tests
        run: cargo test --all-features
        env:
          LD_LIBRARY_PATH: /usr/local/lib/

  clippy:
    name: run clippy lints
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Install Rust
      - uses: dtolnay/rust-toolchain@1.74.1
        with:
          components: clippy

      # Run clippy
      - run: cargo clippy --all-features -- -D warnings

  fmt:
    name: run rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.74.1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
