on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  test:
    name: run tests
    strategy:
      matrix:
        rust: [1.74.1, stable]
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v5

      # Install Rust
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      # Install libopenraw 0.3
      - name: Install dependencies for building libopenraw
        run: |
          sudo apt-get update &&
          sudo apt-get install -y \
             curl build-essential pkg-config libboost-dev \
             libboost-test-dev libjpeg-dev libxml2-dev
      - name: Install libopenraw
        run: |
          curl -O https://libopenraw.freedesktop.org/download/libopenraw-0.3.7.tar.bz2 &&
          tar xf libopenraw-0.3.7.tar.bz2 &&
          cd libopenraw-0.3.7 &&
          ./configure &&
          make -j4 &&
          sudo make install

      # Build
      - name: Build
        run: cargo build --all-features

      # Run tests
      - name: Download test images
        run: python3 tests/download-test-images.py
      - name: Run tests
        run: cargo test --all-features
        env:
          LD_LIBRARY_PATH: /usr/local/lib/

  clippy:
    name: run clippy lints
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v5

      # Install Rust
      - uses: dtolnay/rust-toolchain@1.74.1
        with:
          components: clippy

      # Install libopenraw 0.3
      - name: Install dependencies for building libopenraw
        run: |
          sudo apt-get update &&
          sudo apt-get install -y \
             curl build-essential pkg-config libboost-dev \
             libboost-test-dev libjpeg-dev libxml2-dev
      - name: Install libopenraw
        run: |
          curl -O https://libopenraw.freedesktop.org/download/libopenraw-0.3.7.tar.bz2 &&
          tar xf libopenraw-0.3.7.tar.bz2 &&
          cd libopenraw-0.3.7 &&
          ./configure &&
          make -j4 &&
          sudo make install

      # Run clippy
      - run: cargo clippy --all-features -- -D warnings

  fmt:
    name: run rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.74.1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
