on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  test:
    name: run tests
    strategy:
      matrix:
        rust: [1.40.0, stable]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Install libopenraw
        run: sudo apt-get install libopenraw-dev
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - name: Download test images
        run: python3 tests/download-test-images.py
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  clippy:
    name: run clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.49.0
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  fmt:
    name: run rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.49.0
          override: true
    - run: rustup component add rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
